name: Build docs

permissions: {}

on:
  workflow_call: {}

jobs:
  build-docs:
    name: jekyll github pages build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        persist-credentials: false

    - name: Setup ruby
      uses: ruby/setup-ruby@8d27f39a5e7ad39aebbcbd1324f7af020229645c # v1.287.0
      with:
        ruby-version: '3.3'
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        cache-version: 0 # Increment this number if you need to re-download cached gems
        working-directory: ./docs

    - name: Setup pages
      id: pages
      uses: actions/configure-pages@v5

    - name: Build with Jekyll
      run: bundle exec jekyll build --baseurl "$PAGES_PATH"
      working-directory: ./docs
      env:
        PAGES_PATH: ${{ steps.pages.outputs.base_path }}

    - name: Check links
      run: |
        bundle exec htmlproofer \
          --disable-external \
          --assume_extension '.html' \
          --swap-urls "^${PAGES_PATH}/:/" \
          ./_site
      working-directory: ./docs
      env:
        PAGES_PATH: ${{ steps.pages.outputs.base_path }}

    - name: Upload site assets as artifact
      id: deployment
      uses: actions/upload-pages-artifact@v4
      with:
        path: ./docs/_site
